######################## default configuration ####################
baseURL = "https://beylikduzunakliyat.netlify.app/"
languageCode = "en-us"
title = "Beylikdüzü Nakliyat"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "Hakkında"
  URL = "about"
  weight = 1

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "İletişim"
  URL = "contact"
  weight = 3

  # footer menu
  [[menu.footer]]
  name = "Hakkında"
  URL = "about"
  weight = 1

  [[menu.footer]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "İletişim"
  URL = "contact"
  weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "İstanbul Beylikdüzü Nakliyat"
author = "Admin"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
mobile = "0545 935-3552"
email = "bilgi@kaplanlarnakliyat.com"
location = "Istanbul, Turkey"
# copyright
copyright = " 2021 [Beylikdüzü Evden Eve Nakliyat](https://www.kaplanlarnakliyat.com/hizmetler-Beylikduzu-Nakliyat---Beylikduzu-evden-eve-nakliyat) "

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

